package review

import (
	"fmt"
	"strings"
)

// HeuristicSummarizer is the default Summarizer used when no live agent
// connection is available to call `diff.summarize` against. It counts hunks,
// added/removed lines, and surfaces the first non-trivial change as a sample
// so the mobile UI shows something useful for every file.
//
// Acceptance criterion: "AI summary per file is generated by a `diff.summarize`
// call to the active agent and is cached per file revision." The wiring here
// is the call surface; substituting a real LLM-backed summarizer is a drop-in
// replacement of this struct in cmd/rootmote-agent/main.go.
type HeuristicSummarizer struct{}

// Summarize returns a one-line description of the patch.
func (HeuristicSummarizer) Summarize(projectID, path, patch string) (string, error) {
	if patch == "" {
		return "No textual changes.", nil
	}
	if strings.HasPrefix(patch, "binary file ") {
		return "Binary file changed.", nil
	}
	added, removed, hunks, sample := scanPatch(patch)
	if added == 0 && removed == 0 {
		return "Whitespace or metadata-only change.", nil
	}
	verb := "Modified"
	switch {
	case added > 0 && removed == 0:
		verb = "Added"
	case added == 0 && removed > 0:
		verb = "Removed"
	}
	out := fmt.Sprintf("%s %d / removed %d across %d hunk(s).", verb, added, hunks, hunks)
	if added > 0 && removed > 0 {
		out = fmt.Sprintf("%s %d added, %d removed, %d hunk(s).", verb, added, removed, hunks)
	}
	if sample != "" {
		out += " First change: " + sample
	}
	return out, nil
}

func scanPatch(patch string) (added, removed, hunks int, sample string) {
	for _, ln := range strings.Split(patch, "\n") {
		switch {
		case strings.HasPrefix(ln, "@@"):
			hunks++
		case strings.HasPrefix(ln, "+++"), strings.HasPrefix(ln, "---"):
			// file headers — skip
		case strings.HasPrefix(ln, "+"):
			added++
			if sample == "" && strings.TrimSpace(ln[1:]) != "" {
				sample = trimSample(ln[1:])
			}
		case strings.HasPrefix(ln, "-"):
			removed++
			if sample == "" && strings.TrimSpace(ln[1:]) != "" {
				sample = trimSample(ln[1:])
			}
		}
	}
	return
}

func trimSample(s string) string {
	s = strings.TrimSpace(s)
	if len(s) > 80 {
		return s[:77] + "..."
	}
	return s
}
